# Generated by Django 5.1.3 on 2025-01-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('gerne', models.CharField(max_length=200)),
                ('audio_url', models.CharField(max_length=300)),
                ('duration', models.CharField(max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_image/')),
            ],
        ),
    ]
